CREATE DATABASE Fin
GO
Use Fin
GO
CREATE TABLE [User]
(
   Id UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_User
        PRIMARY KEY CLUSTERED
        DEFAULT NEWID(),
    [Name] NVARCHAR(150) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    [Password] NVARCHAR(500) NOT NULL
);

CREATE TABLE Fund
(
    Id UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_Fund
        PRIMARY KEY CLUSTERED
        DEFAULT NEWID(),

    UserId UNIQUEIDENTIFIER NOT NULL,

    [Limit] DECIMAL(18,2) NOT NULL,

    CONSTRAINT FK_Fund_User
        FOREIGN KEY (UserId)
        REFERENCES dbo.[User] (Id)
);

CREATE TABLE Payment
(
    Id UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_Payment
        PRIMARY KEY CLUSTERED
        DEFAULT NEWSEQUENTIALID(),

    Name NVARCHAR(150) NOT NULL,

    [Date] DATETIME2(0) NOT NULL,

    Installment INT NOT NULL,

    Amount DECIMAL(18,2) NOT NULL,

    InstallmentCount INT NOT NULL,

    FundId UNIQUEIDENTIFIER NOT NULL,

    IsRecurring BIT NOT NULL
        CONSTRAINT DF_Payment_IsRecurring DEFAULT (0),

    IsCredit BIT NOT NULL
        CONSTRAINT DF_Payment_IsCredit DEFAULT (0),

    DateToPay DATETIME2(0) NULL,

    IsPaid BIT NOT NULL
        CONSTRAINT DF_Payment_IsPaid DEFAULT (0),

    CONSTRAINT FK_Payment_Fund
        FOREIGN KEY (FundId)
        REFERENCES dbo.Fund (Id)
);